name: Release PDF

on: [push]

jobs:
  generate-pdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Generate PDF document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/notes.tex
        env:
          TEXINPUTS: ".:./src//:"
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: notes
          path: notes.pdf
  release-generated-pdf:
    name: Release Generated PDF
    runs-on: ubuntu-latest
    needs: generate-pdf
    steps:
      - name: Download PDF
        uses: actions/download-artifact@v2
        with:
          name: notes
          path: .
      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
      - name: Upload PDF to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: notes.pdf
          asset_name: notes-v${{ github.run_number }}.pdf
          asset_content_type: application/pdf
